# Generated by Django 3.2.13 on 2022-10-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='thumb_nail',
            new_name='thumbnail',
        ),
    ]
