# Generated by Django 3.2.13 on 2022-10-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_thumb_nail_review_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
